name:
  en: App Store
  zh: 应用商店
description:
  en: official app store
  zh: 官方应用商店
author: DooTask
website: https://www.dootask.com

entry_points:
  - location: application
    label:
      en: App Store
      zh: 应用商店
    url: apps/appstore/list
    icon: ./logo.svg
